### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by Xchen1995** [ClassmateLin/dm-ticket#11]
<img width="545" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/22890443/f6021669-4f9f-4f75-a773-838a3750940a">

**Comment by Xchen1995** [comment]
不会用docker 只能手动使用rust去跑。。

**Comment by Xchen1995** [comment]
是不是这个url地址要换的 
<img width="556" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/22890443/5abc0d46-13e5-4e92-b015-f98758a13782">

**Comment by Xchen1995** [comment]
大佬回回我！！

**Comment by ClassmateLin** [comment]
请学习使用Docker。

**Comment by ClassmateLin** [comment]
> 不会用docker 只能手动使用rust去跑。。

请学习使用docker.

**Comment by Xchen1995** [comment]
应该和docker没关系吧

**Comment by Xchen1995** [comment]
是rust报错

**Comment by Xchen1995** [comment]
我用docker 
<img width="553" alt="image" src="https://github.com/ClassmateLin/dm-ticket/assets/22890443/7fbd8aaa-bc72-4ffa-9484-49d860eca78b">

**Comment by Xchen1995** [comment]
也报这个错..

**Comment by ClassmateLin** [comment]
> 应该和docker没关系吧

请认真看README.

**Comment by ClassmateLin** [comment]
```
  token-server:
    image: classmatelin/alitoken-server:latest
    restart: always
    container_name: token-server
    networks:
      - dm_network
    environment:
      RUST_LOG: "info"
    ports:
      - "8080:8080"
```
image: classmatelin/alitoken-server:latest 请替换为 image: classmatelin/alitoken-server:v0.1.1
