### ISSUE TITLE
docker-compose zzdns启动错误

### ISSUE THREAD

**Issue by marunrun** [ClassmateLin/dm-ticket#139]
如题。

```yaml
  zzdns:
    volumes:
      - "./zzdns:/usr/local/zzdns/config"
```

首先这里 `./zzdns` 需要改成`./resources/zzdns`

然后不知道是不是我的问题？ 

我的zzdns 启动报错 `Fail to read config file /usr/local/zzdns/../config/config.json`

然后我将后面的挂载地址修改为：`/usr/local/config/` 才启动成功。

所以  `docker-compose.yaml`文件中，`zzdns` 的 `volumes` 我修改之后的完整配置：

```diff
-    volumes:
-      - "./zzdns:/usr/local/zzdns/config"
+    volumes:
+      -  "./resources/zzdns:/usr/local/config/"
```

```yaml
  zzdns:
    # https://github.com/ClassmateLin/zzdns
    image: classmatelin/zzdns:latest
    restart: always
    privileged: true
    container_name: zzdns
    volumes:
      - "./resources/zzdns:/usr/local/config/"
    networks:
      dm_network:
        ipv4_address:  172.88.0.3
    environment:
      RUST_LOG: "info"
``` 

希望对出现同样问题的人有帮助
