### ISSUE TITLE
docker-compose.yml要改一下吧

### ISSUE THREAD

**Issue by Du-gui** [ClassmateLin/dm-ticket#141]
version: '3'
services:
  token-server:
    image: classmatelin/alitoken-server:v0.1.1
    restart: always
    container_name: token-server
    environment:
      RUST_LOG: "info"
    ports:
      - "8080:8080"

**Comment by Du-gui** [comment]
`version: '3'
services:
  token-server:
    image: classmatelin/alitoken-server:v0.1.1
    restart: always
    container_name: token-server
    environment:
      RUST_LOG: "info"
    ports:
      - "8080:8080"`
上面的格式缩减有点问题

**Comment by Du-gui** [comment]
```
version: '3'
services:
  token-server:
    image: classmatelin/alitoken-server:v0.1.1
    restart: always
    container_name: token-server
    environment:
      RUST_LOG: "info"
    ports:
      - "8080:8080"
```
上一个格式缩进有问题
