### ISSUE TITLE
武汉有人成功了么

### ISSUE THREAD

**Issue by Xchen1995** [ClassmateLin/dm-ticket#143]

**Comment by junlinguo11** [comment]
no

**Comment by Kingtous** [comment]
没用

**Comment by xyy19990216** [comment]
4张，但是脚本时间有问题所以抢不到，万幸我手机抢到了

**Comment by areswxin** [comment]
成功了

**Comment by klytsocz17508** [comment]
no

**Comment by xyy19990216** [comment]
@Kingtous 你这个是cookie有问题，时间长了或者你的cookie复制错了

**Comment by chaosicu** [comment]
yes

**Comment by Xchen1995** [comment]
> yes

看看配置..

**Comment by Xchen1995** [comment]
> 成功了

看看配置

**Comment by Xchen1995** [comment]
我又被挤爆了..

**Comment by marunrun** [comment]
难受 根本抢不到

**Comment by crywolfx** [comment]
配置错了， 配置了捡漏时间，原来和开抢时间冲突

**Comment by chaosicu** [comment]
> > yes
> 
> 看看配置..
```
    - cookie: "..."
      remark: 账号1
      # 抢票轮训间隔, 单位毫秒
      interval: 30

      # 最早提前多少毫秒发包。 开抢剩余时间戳 = 开始售票的时间戳 - 当前时间戳。 当开抢剩余时间戳时间小于 submit_time时, 开始发送数据包。
      earliest_submit_time: 0

      # 请求时间 时间戳毫秒 用于捡漏 . 例如 50分是开票时间 但没有抢到,那么这里可以设置55分再抢一次,可能抢到二次放出的票
      # 1685415600100
      request_time: -1

      # 重试次数 
      retry_times: 10

      # 重试间隔 单位毫秒
      retry_interval: 100

      ticket:
        # 需要抢购的门票ID, 门票详情页URL中的itemId.如:https://m.damai.cn/damai/detail/item.html?utm=&itemId=710947802955
        id: "721216860314"
        # 需要抢购的门票数量
        num: 2
        # 需要抢购的场次序号.
        sessions: 2
        # 需要抢购的票档序号
        grade: 3

```
