### ISSUE TITLE
docker卡在正在获取登录二维码

### ISSUE THREAD

**Issue by RugerMcCarthy** [ClassmateLin/dm-ticket#216]
不久后提示登录失败，有什么解决方案嘛

**Comment by shuaiwuyue** [comment]
重试过了么，我第一次启动的时候也卡了很久，后面就好了

**Comment by xisungod** [comment]
用的什么shell啊，我用的powershell，二维码显示的扫不出来来啊

**Comment by xisungod** [comment]
> 重试过了么，我第一次启动的时候也卡了很久，后面就好了

您用的什么shell？

**Comment by shuaiwuyue** [comment]
> > 重试过了么，我第一次启动的时候也卡了很久，后面就好了
> 
> 您用的什么shell？

我在阿里云上租的服务器，centos系统
如果你用的是windows的话，用windows的docker应该可以直接进入容器中，然后直接运行脚本就行了，没有必要使用docker exec命令

**Comment by xisungod** [comment]
？？能给个例子吗？兄弟，docker不熟悉

**Comment by shuaiwuyue** [comment]
你打开docker的Dashboard，然后看到你启动的那个容器，点击之后有个terminal，然后输入dm-client就行

**Comment by xisungod** [comment]
兄弟，为什么获取二维码这么慢

**Comment by ClassmateLin** [comment]
> 兄弟，为什么获取二维码这么慢

基于webdriver操作浏览器扫码登录的，是会慢点。 docker-compose限制了cpu和内存资源。可适当提高试试。

```
version: "3"

services:
  dm-ticket:
    image: classmatelin/dm-ticket:latest
    container_name: dm-ticket
    restart: always
    privileged: true
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 600M
        reservations:
          cpus: '0.5'
          memory: 300M

```
